name: "Pre-release"

on:
  push:
    branches:
      - "*"

jobs:
  pre-release:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Jar file
        run: ./gradlew clean build shadowJar